#####################################
#
# Schemas and Scripts for Greenhouse Tables
#
#####################################

# Table 1 (companies): company_id (serial pk), company_name (str)
#
#
# Table 2 (jobs): job_id (serial pk), company_id (linked), job_title,
#                 location, posted_date, updated_date, salary_low, salary_high, url
#
#
# Table 3 (skills): skill_id (serial pk), skill_name
#
#
# Table 4 (job_skills): job_id (linked), skill_id (linked)
#





#####################################
#
# Creation Scripts
#
#####################################

create_companies = '''CREATE TABLE IF NOT EXISTS companies(                  
                          company_id              SERIAL           PRIMARY KEY ,
                          company_name            VARCHAR(100)     NOT NULL )'''

create_jobs = '''CREATE TABLE IF NOT EXISTS jobs(
                          job_id                  SERIAL         PRIMARY KEY ,
                          greenhouse_job_id       BIGINT         UNIQUE NOT NULL ,
                          internal_job_id         BIGINT         NOT NULL ,
                          company_id              BIGINT         REFERENCES companies(company_id) ,
                          job_title               VARCHAR(200)   NOT NULL ,
                          location                VARCHAR(200)   NOT NULL , 
                          posted_date             TIMESTAMP      NOT NULL ,
                          updated_date            TIMESTAMP , 
                          salary_low              INTEGER , 
                          salary_high             INTEGER ,
                          url                     VARCHAR(100)   UNIQUE NOT NULL )'''

create_skills = '''CREATE TABLE IF NOT EXISTS skills(
                          skill_id     SERIAL         PRIMARY KEY , 
                          skill_name   VARCHAR(100)   NOT NULL )'''

create_job_skills = '''CREATE TABLE IF NOT EXISTS job_skills(
                          job_id       BIGINT      REFERENCES jobs(job_id) ,
                          skill_id     BIGINT      REFERENCES skills(skill_id) )'''

#####################################
#
# Add/Update Row Scripts for Each Table
#
#####################################

add_company = '''INSERT INTO companies(company_name) 
                 VALUES (%s)
                 RETURNING company_id'''

add_job = '''INSERT INTO jobs(greenhouse_job_id, internal_job_id, company_id, 
                              job_title, location, posted_date, updated_date, url) 
             VALUES(%s,%s,%s,%s,%s,%s,%s,%s)
             RETURNING job_id'''

add_skill = 'INSERT INTO skills(skill_name) VALUES(%s) RETURNING skill_id'

add_job_skill = 'INSERT INTO job_skills(job_id, skill_id) VALUES(%s,%s)'

update_company = ''

update_job = ''

#####################################
#
#
#
#####################################


#####################################
#
# Lists for Greenhouse Tables:
#
#####################################

greenhouse_table_names = ('companies','jobs','skills','job_skills')


#####################################
#
# Lists of Companies
#
#####################################



fortune_500s_california = [
    'Live Nation Entertainment',
    'Walt Disney',
    'Monster Beverage',
    'Ross Stores',
    'A-Mark Precious Metals',
    'Gilead Sciences',
    'TD Synnex',
    'Lam Research',
    'Ingram Micro',
    'Molina Healthcare',
    'Netflix',
    'Skechers U.S.A.',
    'Meta',
    'KLA',
    'Sandisk',
    'Alphabet',
    'Intuit',
    'Concentrix',
    'Pacific Life',
    'Chipotle Mexican Grill',
    'PG&E',
    'Block',
    'Broadcom',
    'HP',
    'Workday',
    'Equinix',
    'Edison International',
    'Qualcomm',
    'LPL Financial',
    'Sempra',
    'Wells Fargo',
    'Uber',
    'Salesforce',
    'Visa',
    'Gap',
    'DoorDash',
    'Airbnb',
    'Prologis',
    'Cisco Systems',
    'PayPal',
    'Adobe',
    'Super Micro Computer',
    'Ebay',
    'Western Digital',
    'Sanmina',
    'Franklin Resources',
    'Nvidia',
    'Intel',
    'Advanced Micro Devices',
    'Applied Materials',
    'ServiceNow',
    'Palo Alto Networks',
    'Arista Networks',
    'Marvell Technology',
    'Intuitive Surgical',
    'Synopsys',
    'Amgen',
    'Farmers Insurance Exchange']

remote_companies = [
    'Lockheed Martin',
    'Marsh McLennan Agency',
    'Marriott International',
    'SAIC',
    'Humana',
    'Verizon',
    'Optum',
    'AECOM',
    'State of Michigan',
    'WSP',
    'Compass',
    'Centene',
    'PNC Financial',
    'Conduent',
    'Amentum',
    'Elevance Health',
    'Amgen',
    'Amazon.',
    'GE Healthcare',
    'CIBC',
    'Concentrix',
    'Banner Health',
    'Northrop Grumman',
    'DoorDash',
    'Google',
    'CVS Health',
    'ServiceNow',
    'Stantec',
    'Oracle',
    'Leidos',
    'Alberta Health',
    'Workday',
    'Allstate Insurance',
    'Cognizant Technology',
    'Meta',
    'S&P Global',
    'IQVIA',
    'Morgan Stanley',
    'Tetra Tech',
    'Honeywell',
    'Tenet Healthcare',
    'Cardinal Health',
    'Capital One',
    'Johnson & Johnson',
    'Wells Fargo',
    'ADP',
    'Cisco',
    'Thermo Fisher Scientific',
    'Northwestern Mutual',
    'Coldwell Banker',
    'TELUS',
    'Mercer',
    'General Dynamics (IT)',
    'Ascension',
    'Abbott',
    'FedEx Logistics',
    'Thomson Reuters',
    'Comcast',
    'Microsoft',
    'GEICO',
    'Children’s Mercy',
    'DXC Technology',
    'M&T Bank',
    'Warner Bros Discovery',
    'Visa',
    'Raytheon',
    'John Deere',
    'Ford Motor',
    'Baxter Woodman',
    'Cushman & Wakefield',
    'Kaiser Permanente',
    'Truist',
    'Best Buy',
    'State Street',
    'Aramark',
    'Motorola Solutions',
    '3M',
    'Coldwell Banker Schmidt',
    'EPAM Systems',
    'SAP',
    'Fidelity Investments',
    'UnitedHealthcare',
    'NBCUniversal',
    'UST',
    'Mastercard',
    'Marsh McLennan (corp)',
    'T‑Mobile',
    'TD',
    'AT&T',
    'Pfizer',
    'GE Aerospace',
    'JLL',
    'Spectrum',
    'Gartner',
    'AbbVie',
    'Mondelēz International',
    'Medtronic',
    'FIS',
    'Scotiabank',
    'Bell Canada']

remote_firsts = [
    '10up',
    '37signals',
    'Automattic',
    'AwesomeMotive',
    'BairesDev',
    'Bandcamp',
    'BandLab',
    'Buffer',
    'Bunny.net',
    'Canonical',
    'Chef',
    'chess.com',
    'Cloudbeds',
    'Cloudbees',
    'Codelathe',
    'ConsenSys',
    'Crossover',
    'DataDog',
    'DataRobot',
    'Deel',
    'Doist',
    'Dribbble',
    'DuckDuckGo',
    'Elastic',
    'End Point Dev',
    'Envato',
    'Eyeo',
    'Fireflies.ai',
    'Gatsby',
    'Genuitec',
    'Ghost',
    'GitLab',
    'Gradle',
    'Grafana Labs',
    'Help Scout',
    'Hubstaff',
    'Igalia',
    'Jackson River',
    'Jitbit Software',
    'Kentik',
    'Kraken',
    'Lullabot',
    'madewithlove',
    'MailerLite',
    'MarsBased',
    'Mobile Jazz',
    'Mozilla',
    'Netlify',
    'Olark',
    'Original Eight',
    'Percona',
    'Platform.sh',
    'Pythian',
    'RedHat',
    'Redox',
    'Remote',
    'SaasGroup',
    'ScyllaDB',
    'Shogun',
    'Shopify',
    'Sonatype',
    'Sourcegraph',
    'Spotify',
    'Square',
    'Superside',
    'Time Doctor',
    'Toggl',
    'Toptal',
    'Turing',
    'Upwork',
    'Vercel',
    'Wikimedia',
    'X-team',
    'Xapo',
    'XWP',
    'You Need A Budget',
    'Zapier',
    'Zyte']

greenhouse_companies = [
    'affirm',
    'consensys',
    'netlify',
    'cloudbeds',
    'elastic',
    'datadog',
    'turing',
    'wikimedia',
    'upwork',
    'gradle',
    'vercel',
    'airbnb',
    'gitlab',
    'mozilla',
    'saasgroup',
    'kentik',
    'canonical',
    'eyeo',
    'ghost',
    'block',
    'remote' ]

skills_list = {
    "data analyst":[
       'SQL',
       'PostgreSQL',
       'MySQL',
       'Microsoft SQL Server',
       'SQLite',
       'Oracle SQL',
       'Python',
       'pandas',
       'NumPy',
       'R',
       'Excel',
       'Power BI',
       'Tableau',
       'Looker',
       'Google Looker Studio',
       'Data Visualization',
       'Data Cleaning',
       'Data Wrangling',
       'Data Analysis',
       'Exploratory Data Analysis',
       'Statistical Analysis',
       'Business Intelligence',
       'Business Analytics',
       'Reporting',
       'Dashboard Development',
       'ETL',
       'Data Modeling',
       'Relational Databases',
       'Database Design',
       'Data Warehousing',
       'Data Validation',
       'Data Quality',
       'Data Governance',
       'Data Mining',
       'Data Transformation',
       'Feature Engineering',
       'A/B Testing',
       'Hypothesis Testing',
       'Regression Analysis',
       'Time Series Analysis',
       'Predictive Analytics',
       'Machine Learning',
       'scikit-learn',
       'Jupyter Notebook',
       'Git',
       'GitHub',
       'Linux',
       'Bash',
       'REST APIs',
       'JSON',
       'CSV',
       'XML',
       'Web Scraping',
       'Regular Expressions',
       'Power Query',
       'DAX',
       'Pivot Tables',
       'VLOOKUP',
       'XLOOKUP',
       'Excel Power Pivot',
       'Window Functions',
       'Common Table Expressions (CTEs)',
       'Stored Procedures',
       'Views',
       'Indexes',
       'Query Optimization',
       'Snowflake',
       'BigQuery',
       'Redshift',
       'Azure Synapse',
       'Databricks',
       'dbt',
       'Apache Airflow',
       'Apache Spark',
       'PySpark',
       'AWS',
       'Azure',
       'Google Cloud Platform',
       'Stakeholder Communication',
       'Requirements Gathering',
       'KPI Development',
       'Data Storytelling' ] ,
    "data scientist":[] ,
    "data engineer": [
       'SQL',
       'PostgreSQL',
       'MySQL',
       'Microsoft SQL Server',
       'Oracle',
       'SQLite',
       'Python',
       'Java',
       'Scala',
       'Go',
       'Bash',
       'Linux',
       'Git',
       'GitHub',
       'Docker',
       'Kubernetes',
       'Apache Airflow',
       'Apache Spark',
       'PySpark',
       'Apache Kafka',
       'Apache Hive',
       'Apache Hadoop',
       'Apache Flink',
       'Apache Beam',
       'dbt',
       'ETL',
       'ELT',
       'Data Pipelines',
       'Workflow Orchestration',
       'Data Modeling',
       'Dimensional Modeling',
       'Data Warehousing',
       'Data Lakes',
       'Lakehouse',
       'Data Lakehouse',
       'Data Integration',
       'Data Transformation',
       'Data Validation',
       'Data Quality',
       'Data Governance',
       'Metadata Management',
       'Master Data Management',
       'Schema Design',
       'Database Design',
       'Database Administration',
       'Query Optimization',
       'Performance Tuning',
       'Indexing',
       'Partitioning',
       'Stored Procedures',
       'Window Functions',
       'Common Table Expressions (CTEs)',
       'Views',
       'AWS',
       'Amazon S3',
       'Amazon Redshift',
       'Amazon RDS',
       'AWS Glue',
       'AWS Lambda',
       'AWS Athena',
       'Azure',
       'Azure Data Factory',
       'Azure Synapse',
       'Azure Databricks',
       'Google Cloud Platform',
       'BigQuery',
       'Cloud Storage',
       'Snowflake',
       'Databricks',
       'Delta Lake',
       'Apache Iceberg',
       'Apache Hudi',
       'Parquet',
       'Avro',
       'ORC',
       'JSON',
       'CSV',
       'XML',
       'REST APIs',
       'GraphQL',
       'CI/CD',
       'GitHub Actions',
       'Jenkins',
       'Terraform',
       'Infrastructure as Code',
       'Monitoring',
       'Logging',
       'Observability',
       'Prometheus',
       'Grafana',
       'Data Security',
       'Data Privacy',
       'IAM',
       'Automation',
       'Shell Scripting',
       'Object-Oriented Programming',
       'Distributed Systems',
       'Parallel Processing',
       'Streaming Data',
       'Batch Processing',
       'Real-Time Data Processing',
       'NoSQL',
       'MongoDB',
       'Redis',
       'Cassandra',
       'Elasticsearch',
       'DuckDB',
       'Polars',
       'pandas',
       'NumPy' ]
}


